### ISSUE TITLE
Replace existing notifications

### ISSUE THREAD

**Issue by GideonWolfe** [dcx86r/cmus-notify#2]
I find that if I am rapidly operating `cmus`, my notifications will stack up like so;

![image](https://user-images.githubusercontent.com/32942052/103465374-c02cfa80-4cef-11eb-9236-c47f4a5ff0f3.png)

I believe `notify-send` has a `-r` flag which allows you to replace an existing notification that has been assigned an `ID` (integer).

So basically when a `cmus` notification pops up, it will replace the one that already exists. This is how people make volume/brightness indicators, same principal.

I would write the PR myself but i'm not great with `perl`. But I can give it a shot if you want.

**Comment by GideonWolfe** [comment]
Correction, it doesn't look like `notify-send` has this feature by default. `dusntify` does though, which is a drop in replacement for `notify-send` if you happen to be using `dunst` for notifications (which I am).

I'm new to `perl` and tried adding 

```perl
  push(@args, "-r 10");
```
right before the notification is fired off, but this seems to break the script (even though running it from the command line produces no errors).

**Comment by BigRedS** [comment]
You'll want
```push(@args, '-r', '10');```
since it's two arguments (a `-r` and a `10`).

Per this reddit thread, which is how I got here:
https://www.reddit.com/r/perl/comments/l2wc9r/could_someone_help_me_edit_an_argument_for_this/

**Comment by dcx86r** [comment]
Sorry for not responding sooner, and thanks for bringing this feature to my attention! I'm not sure if there's a way to replicate it with `notify-send` but I can add `dunstify` as an option when I have some time within the next few days.

**Comment by dcx86r** [comment]
This feature is now supported through the `dunst` config option, described in the README. I like it!
